---

- name: Reboot the server
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for system to come back
  local_action:
    module: wait_for
      host="{{ ansible_host }}"
      port="{{ ansible_port|default(22) }}"
      delay=10
      state="started"
      timeout=300

