---

- name: Add user
  user: name={{ adduser_user_name }} password="{{ adduser_password }}" comment="{{ adduser_user_comments }}" shell=/bin/bash
  become: yes
  when: ansible_distribution != 'OpenBSD' and ansible_os_family != 'Darwin' and ansible_os_family != "Alpine"

## try to keep compatibility with 1.9.6
#- block:
- name: Alpine | Add user
  command: "adduser -D {{ adduser_user_name }} creates=/home/{{ adduser_user_name }}"
  become: yes
  ignore_errors: true
  when: ansible_os_family == "Alpine"
## else newly created account is locked
- name: Alpine | Unlock user
  command: "passwd -u {{ adduser_user_name }}"
  ignore_errors: true
  when: ansible_os_family == "Alpine"

- name: OpenBSD | Add user
  user: name={{ adduser_user_name }} shell=/bin/ksh
  become: yes
  when: ansible_distribution == 'OpenBSD'

## FIXME! not idempotent
- name: darwin | Add user (admin)
  user: name={{ adduser_user_name }} password="{{ adduser_password }}" comment="{{ adduser_user_comments }}" shell=/bin/bash groups=admin append=yes
  when: ansible_os_family == 'Darwin' and adduser_sudoroot is defined and adduser_sudoroot
  become: yes
#- name: darwin | add user to admin group
#  command: "dscl . append /Groups/admin GroupMembership {{ adduser_user_name }}"
#  when: ansible_os_family == 'Darwin' and adduser_sudoroot is defined and adduser_sudoroot
- name: darwin | Add user (std)
  user: name={{ adduser_user_name }} password="{{ adduser_password }}" comment="{{ adduser_user_comments }}" shell=/bin/bash
  when: ansible_os_family == 'Darwin' and not (adduser_sudoroot is defined and adduser_sudoroot)
  become: yes

- name: check home has correct permissions
  file: "dest={{ adduser_user_home }} owner={{ adduser_user_name }} mode={{ adduser_user_home_perms }} state=directory"
  become: yes

- debug: var=adduser_public_keys
- name: Add authorized keys for {{ adduser_user_name }} user
  authorized_key:
    "user='{{ adduser_user_name }}' key='{{ item }}'"
  with_file: "{{ adduser_public_keys }}"
  when: adduser_public_keys is defined and adduser_public_keys != "" and adduser_sshkey_options is not defined
  become: yes
- name: Add authorized keys for {{ adduser_user_name }} user - key_options
  authorized_key:
    user: "{{ adduser_user_name }}"
    key: "{{ item }}"
    key_options: "{{ adduser_sshkey_options }}"
  with_file: "{{ adduser_public_keys }}"
  when: adduser_public_keys is defined and adduser_public_keys != "" and adduser_sshkey_options is defined
  become: yes

- name: SSH authorized_keys {{ adduser_user_name }}
  file:
    dest={{ adduser_user_home }}/.ssh owner={{ adduser_user_name }} mode=700 state=directory
  become: yes
  when: ansible_distribution != 'OpenBSD' and ansible_os_family != 'Darwin'

- stat: path=/etc/sudoers
  register: sudoers
- name: Add user to sudoers
  lineinfile: "dest=/etc/sudoers regexp='^{{ adduser_user_name }} ALL' line='{{ adduser_user_name }} ALL=(ALL) NOPASSWD: ALL' state=present"
  when: adduser_sudoroot is defined and adduser_sudoroot and sudoers.stat.exists
  become: yes

