---
- name: Replace Volumio logo in assets/variants/volumio/
  stat: path=/volumio/http/www/app/themes/volumio/assets/variants/volumio/graphics/volumio-logo.png
  register: variants_path
  tags: logo
- file:
    src: volumio-logo.png
    dest: /volumio/http/www/app/themes/volumio/assets/variants/volumio/graphics/volumio-logo.png
    state: file
    owner: volumio
    group: volumio
    mode: 0644
  when: variants_path.stat.exists == True
  tags: logo

- name: Replace volumio logo in assets
  stat: path=/volumio/http/www/app/themes/volumio/assets/graphics/volumio-logo.png
  register: assets_path
  tags: logo
- file:
    src: volumio-logo.png
    dest: /volumio/http/www/app/themes/volumio/assets/graphics/volumio-logo.png
    state: file
    owner: volumio
    group: volumio
    mode: 0644
  when: assets_path.stat.exists == True
  tags: logo

- name: Changing the values in the stylesheet(s)
  include_tasks: stylesheet.yml
  tags: css

- name: Add web-radio station to favourites
  include_tasks: webradio.yml
  tags: radio

- name: Put a password on Airplay
  include_tasks: airplayww.yml
  tags: airplay

