---
- name: Get the squeezelite file from template
  become: yes
  template:
    src: squeezelite.j2
    dest: /etc/init.d/squeezelite
    owner: volumio
    group: volumio
    mode: 0755
  tags: squeezelite

- name: Get the squeezelite-armv6hf command file
  become: yes
  file:
    src: squeezelite-armv6hf
    dest: /usr/bin/squeezelite-armv6hf
    owner: volumio
    group: volumio
    mode: 0755
  tags: squeezelite


