---
# this is the additional_packages playbook for the common role

- name: Install mailutils
  become: yes
  apt: name=mailutils state=present
  tags: mailutils

- name: Install ssmtp
  become: yes
  apt: name=ssmtp state=present
  tags: ssmtp

- name: Install bzip2
  become: yes
  apt: name=bzip2 state=present
  tags: bzip2

- name: Install vim
  become: yes
  apt: name=vim state=present
  tags: vim

