---
# this is the cron playbook for all nodes

- name: Install cron
  become: yes
  apt: name=cron state=present
  tags: cron

- name: Start the cron service
  become: yes
  service: name=cron state=started enabled=yes
  tags: cron


