---
- name: Install and start the NTP services
  include_tasks: ntp.yml
  tags: ntp
- name: Prevent ssh login without key-pair
  include_tasks: nopwlogon.yml
  tags: ssh
- name: Install and start the cron service
  include_tasks: cron.yml
  tags: cron
- name: Add additional services
  include_tasks: additional_services.yml

- name: Install motd from template
  template:
    src: motd.j2
    dest: /etc/motd
    owner: volumio
    group: volumio
    mode: 0644
  tags: motd

- name: Add ssmtp-configuration from template
  become: yes
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  tags: ssmtp
- name: Define the mail files from templates
  template:
    src: mail.txt.j2
    dest: /home/volumio/mail.txt
    owner: volumio
    group: volumio
    mode: 0644
  tags: ssmtp,mail
- name: Define the mailIP script files from template
  template:
    src: mailIP.sh.j2
    dest: /home/volumio/mailIP.sh
    owner: volumio
    group: volumio
    mode: 0755
  tags: ssmtp,mail
- name: Define the ialogin mail file from template
  template:
    src: ialogin.txt.j2
    dest: /home/volumio/ialogin.txt
    owner: volumio
    group: volumio
    mode: 0644
  tags: ssmtp,mail
- name: Add script to mail an interactive login
  become: yes
  template:
    src: ialogin.sh.j2
    dest: /etc/profile.d/ialogin.sh
    owner: volumio
    group: volumio
    mode: 0755
  tags: ssmtp,mail
- name: Add mail-me-the-IP-address to startup of the system
  become: yes
  lineinfile:
    path: "/etc/rc.local"
    regexp: "mailIP"
    insertbefore: "^exit 0"
    line: "/bin/sleep 20;/home/volumio/mailIP.sh\n"
    state: present
  tags: ssmtp,mail

