---
- name: Configure the MusicPlayers
  template:
    src: motd.j2
    dest: /etc/motd
    owner: volumio
    group: volumio
    mode: 0644
- include_tasks: ntp.yml
- include_tasks: nopwlogon.yml
- include_tasks: cron.yml
- include_tasks: additional_services.yml
- name: Add ssmtp-configuration from template
  become: yes
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644
- name: Define the mail template files
  template:
    src: mail.txt.j2
    dest: /home.volumio/mail.txt
    owner: volumio
    group: volumio
    mode: 0644
- name: Define the mailIP script files
  template:
    src: mailIP.sh.j2
    dest: /home.volumio/mailIP.sh
    owner: volumio
    group: volumio
    mode: 0755

