---
- name: Restrict ssh logon to authorized keys PasswordAuth)
  become: yes
  lineinfile: path='/etc/ssh/sshd_config'
              line='PasswordAuthentication no'
              state=present
  notify: restart sshd
  tags: ssh

- name: Set PAM=no settings
  become: yes
  lineinfile: path='/etc/ssh/sshd_config'
              line='UsePAM no'
              state=present
  notify: restart sshd
  tags: ssh

#- name: Do not use PAM=yes setting
#  become: yes
#  lineinfile: path='/etc/ssh/sshd_config'
#              line='UsePAM yes'
#              state=absent
#  notify: restart sshd
#  tags: ssh

- name: Restrict ssh logon to authorized keys (ChallengeRespAuth)
  become: yes
  lineinfile: path='/etc/ssh/sshd_config'
              line='ChallengeResponseAuthentication no'
              state=present
  notify: restart sshd
  tags: ssh

- name: Make sure there is a .ssh directory
  file:
    path: /home/volumio/.ssh/
    state: directory
    owner: volumio
    group: volumio
    mode: 0700
  tags: ssh

- name: Copy authorized_keys to .ssh
  copy:
    src: authorized_keys
    dest: /home/volumio/.ssh/authorized_keys
    owner: volumio
    group: volumio
    mode: 0600
  tags: ssh


