---
- name: Restrict ssh logon to authorized keys PasswordAuth)
  become: yes
  lineinfile: path='/etc/ssh/sshd_config'
              insertafter='^#PasswordAuthentication yes'
              line='PasswordAuthentication no'
              state=present
  notify: restart sshd
  tags: ssh

- name: Make sure there is a .ssh directory
  file:
    path: /home/volumio/.ssh/
    state: directory
    owner: volumio
    group: volumio
    mode: 0700
  tags: ssh

- name: Copy authorized_keys to .ssh
  template:
    src: authorized_keys.j2
    dest: /home/volumio/.ssh/authorized_keys
    owner: volumio
    group: volumio
    mode: 0600
  tags: ssh


