---
- debug:
    msg: "Rebooting server {{ ansible_host }} and wait for it to come back"

- name: Reboot the server
  become: yes
  shell: reboot
  async: 0
  poll: 0
  ignore_errors: true
  register: reboot

- name: Wait for system to come back
  local_action:
    module: wait_for
      host="{{ ansible_host }}"
      port="{{ ansible_port|default(22) }}"
      delay=10
      state="started"
      timeout=300

- name: Get facters
  setup:

- debug:
    msg: "We're back! Running on {{ inventory_hostname }}"

- name: capture output of id command
  command: id -un
  register: login
- debug: var=login
  no_log: True
- debug: var=login.stdout
