---

adduser_user_name: ansible
adduser_user_home: '/home/ansible'
adduser_user_home_perms: '0700'
adduser_user_comments: ""
adduser_sudoroot: true
adduser_password: 'ansible'

adduser_public_keys:
- nico-hp.pub
- nico-thinkpad.pub

